const PROFILES=['Control de Stock','Empleado','Encargado','Operaciones','Propietario','Recepcionista','Soporte'];
const raw={
'AGENDA':`Cambiar notas de visita de otros empleados|Cambiar tamaño de cita|Cambiar tamaño de tarea|Change Appointment Service|Crear cita|Crear cita con el asistente|Crear tarea|Create Employee Filter|Delete Employee Filter|Edit Employee Filter|Eliminar cita|Eliminar tarea|Modificar coste de cancelación|Mover cita|Mover tarea|Puede exceder tiempo límite reservado|Quitar “completo” en notas de visita|Repetir cita|Repetir tarea|Reprogramar cita|Superar la capacidad de una clase`,
'AYUDA':`Ayuda`,
'CLIENTES':`Actualizar puntos de cliente|Cancel Membership|Edit Client Photo History|Eliminar cliente|Imprimir FPC|Refund Membership|Resubscribe Membership|Suspend Membership|Ver detalles de cliente desenmascarados|Waive Membership`,
'CONFIGURACIÓN':`Añadir habilidades|Cambiar comisiones del empleado|Cambiar detalles de empleados|Cambiar empleados de habilidades|Cambiar habilidades|Cambiar posición del empleado|Configurar categorías de recursos|Eliminar habilidades`,
'COPIA DE SEGURIDAD':`Copia de seguridad`,
'HORARIO':`Añadir entrada del horario|Cambiar horas actuales|Cambiar horas programadas|Eliminar entrada del horario`,
'PERMITIR SMS DIRECTOS':`Permitir SMS directos|Puede ser conectado/desconectado`,
'PUNTO DE VENTA':`Abrir el cajón (permitirlo sin venta)|Anular transacción|Assign alternate loyalty card|Borrar una transacción|Cambiar empleado en transacción completada|Cambiar la fecha del listado de transacciones|Cambiar precio en el PDV - Extras|Cambiar precio en el PDV - Productos|Cambiar tipo de pago de la transacción|Canjear vales de regalo caducados|Canjear vales de regalo sin seguimiento|Change Price at Service Selection|Permitir descuento de línea - Extra|Permitir descuento de línea - Productos|Permitir descuento de línea - Servicios|Permitir descuento en venta|Permitir devolución de pagos a cuenta|Permitir excluir impuestos en el PDV|Puede seleccionarse en el PDV|Redeem Member Benefits Offline|Reembolsar transacción|Remove Surcharge|Revender|Sobrescribir contraindicaciones cliente|Terminar venta|Vender a #EMPRESA|Vender a #GASTOS|Vender a #TRABAJADORES|Vender a #VENTA y #WALKIN|Ver ingresos de hoy`,
'SEGURIDAD':`Activar o desactivar seguridad|Borrar el registro|Cambiar el PIN de otro empleado|Cambiar huella de otro empleado|Can Upgrade|Change own PIN|Conectar y desconectar otros empleados|Configurar la contraseña de inicio|Huella dactilar puede ser asignada|Permitir PIN al inicio|Salir del programa`,
'SERVICIO':`Cambiar detalles de bonos|Cambiar detalles de servicios|Cambiar precio servicio|Cambiar servicios de habilidades|Canjear bonos caducados`,
'STOCK':`Cambiar cantidad de stock|Cambiar código de barras del producto|Cambiar configuración de reorder|Cambiar coste medio|Cambiar detalles de stock|Cambiar el precio de venta de producto|Cambiar precio de compra del producto|Crear productos|Ver precio de compra de stock|Ver stock en mano`,
'VISIT NOTE TYPES':`Anulación|Cambios|Cuentas|Folio Autorización|Vales de Regalo|Visit Notes`,
'REPORTS':`Change Historical Visit Notes|Change Other Employee Visit Notes|Change Own Visit Notes|Create Historical Visit Notes|Create Visit Notes|Delete Other Employee Visit Notes|Delete Own Visit Notes|View Other Employee Visit Notes`,
'REPORTES':`Opciones de anulaciones|Opción de borrado de citas|Opción de borrar clientes|Redención de puntos de fidelidad|Eliminar transacciones|Cambio de precio|Sin opción de registro del sistema|Importar/Exportar`
};
const reportGroups={
'Caja del día':`Balance de sesión|Balance del día|Desglose de transacciones|Movimientos de efectivo|Pagos externos incompletos|Registro de empresa|Sumario de movimientos`,
'Citas':`Análisis de citas y horario|Asistencia a clases|Citas|Contraindicaciones de la cita|Estadísticas de la lista de espera|Estadísticas de los no presentados|Estadísticas del servicio ReservaMe|Historial de citas|Llegadas de cliente|Programación de recursos|Uso de etiquetas|Valor de las citas futuras`,
'Clientes':`Actividad de las referencias|Citas canceladas|Clientes no retornados desde un rango|Clientes que más gastan|Datos demográficos del cliente|Informe de referencias de clientes|Precisión de datos de clientes`,
'Empleados':`Auditoría de recogida de tarjetas|Citas futuras|Clasificación|Desglose de Re-Reservas|Desglose diario|Desglose mensual|Desglose semanal|Horario semanal|Horas empleados|Horas por tipos de horario|Informe de salarios y comisiones|Productos por empleado|Propinas|Recordatorios de notas de visita|Retención de clientes (90 días)|Servicios por empleado|Sumario de rendimiento|Sumario de rendimiento - Extendido|Sumario de salarios especiales|Sumario de ventas por empleado|Trabajo vs ventas|Visitas programadas de clientes por empleado`,
'Empresa':`Actividad de la promoción|Análisis de frecuencia de visita|Beneficios y pérdidas|Comparación de recaudaciones|Desglose de empresa por categoría de información|Desglose de planta|Desglose de recaudaciones|Estrictamente de empresa|Informe de cuentas de clientes|Informe de impuestos|Informe de objetivo de empresa|Lista de clientes por número de lote|Lista promoción|Notas de crédito|Pagos por adelantado|Pagos por recibir caducados|Pasivo consolidado|Pasivo de venta de bonos|Puntos pendientes de clientes|Rendimiento de empleado de la empresa|Rendimiento del negocio del centro|Revisión de eliminación de visita|Sumario de ventas de la empresa|Tendencia de ventas|Vales de regalo pendientes|Vales de regalo caducados|Vales de regalo por caducar|Ventas por terminal`,
'Servicios':`Desglose de categoría de puntos de clientes|Desglose de servicios con niveles|Desglose de servicios por categoría|Servicios más vendidos`,
'Stock':`Cambiar precio de venta de producto|Desglose de ventas de productos|Etiquetas de producto para estanterías|Formulario de artículos no listados|Historial de movimientos de stock|Informe de control de stock|Informe de inventario|Informe de mantenimiento de stock|Listado de precios de productos|Pedidos pendientes|Productos más vendidos|Rendimiento de productos|Rendimiento de ventas por compañía|Stock recibido|Sumario de stock recibido|Sumario de ventas de productos|Uso de stock por servicio|Uso de stock profesional`,
'Transacciones':`Desglose de ingresos extras|Desglose de razones de descuento|Desglose de tipos de pago|Gastos|Lista de reembolsos|Listado de reembolsos por empleado|Mejores ventas|PMS Pagos de cuentas de huéspedes|Razones de descuento por empleado|Tarifas de cancelación|Transacciones anuladas|Transacciones de cliente por club|Transacciones diarias|Transacciones por empleado|Uso de vales de regalo`,
'Varios/Formularios':`Formulario de cliente nuevo|Formulario para stock no listado|Informe de mantenimiento de stock|Informe de seguridad|Lista de emergencia|Lista de nuevos rápidos|Listado de recursos|Recibo de cortesía A4|Recibo de cortesía A5`,
'Walkin Manager':`Comparación de eficiencia del rango|Datos demográficos del rango|Eficiencia de empleado|Eficiencia de los servicios por empleado|Eficiencia del rango|Estado de las visitas|Visitas abandonadas`};
raw['ITEMS / REPORTES']=Object.entries(reportGroups).flatMap(([g,s])=>s.split('|').map(x=>`${g}: ${x}`)).join('|');
const screens={
'Agenda':`Agenda|Cancelación|En tienda|Uso de confirmaciones`,'Arrivals Screen':'','Asistencia de los empleados':'',
'Clientes':`Conf. campos personalizados del cliente|Editar ficha de cliente personalizada|Ficha detalles de cliente|Fusión de clientes|Historial de cliente|Historial de Fotos|Listado de clientes|Treatment|Ver ficha personalizada de cliente`,
'Configuración':`Conf. regional|Config. Bonos|Config. Procesador de Pagos|Configuración de cliente|Configuración de club|Configuración de confirmación|Configuración de contraindicación|Configuración de descuento|Configuración de gastos|Configuración de grupos de empleados|Configuración de impuestos|Configuración de Ingresos Extras|Configuración de internet|Configuración de la empresa|Configuración de la promoción|Configuración de plantillas de horario|Configuración de privacidad de datos|Configuración de recibo|Configuración de recursos|Configuración de seguridad|Configuración de vales de regalo|Configuración del código postal|Configuración del punto de venta|Configuración del terminal|Configuración del tipo de pago|Configuración del Walkin|Configuraciones de stock|Configuraciones generales|Configurar habilidades de empleados|Membership Setup|Pantalla de clientes|Pantalla de servicios|Visit Note Types Setup`,
'Configuración de especiales':'','Etiquetas':`Apply Appointment/WIM Tag|Change Appointment/WIM Tag|Crear etiqueta|Editar etiqueta|Eliminar etiqueta`,'Horario':'','Importar/Exportar':'','Informes':'','Internet':'','Marketing':'','Notas de cita':`Crear nota de cita|Editar nota de cita|Eliminar nota de cita`,'PowerSalon':`Informe creador de dinero|Mind Focus|PowerSalon|Programa Recompensas|Registro Recompensas`,'Punto de Venta':`Eliminar cliente del PDV|Finalizar sesión|Generar envío de archivos de tarjetas|Gestionar movimientos de efectivo|Iniciar sesión|Listado de transacciones|Permitir ajustes de propina|Puede transferir propinas a empleados|Punto de Venta`,'Reg. de seguridad':`Ver reg.`,'Rendimiento del trabajador':'','Soporte por internet':'','Stock':`Cambiar pedido recibido|Desempaquetar|Empaquetar|Inventario|Pantalla de productos|Pedidos`,'Statistics Calculation':'','Tasks':`Create Task|Delete Task|Edit Task`,'Walkin Manager':`Walkin Manager`};
let permissions=[];let seq=0;
Object.entries(raw).forEach(([module,names])=>names.split('|').filter(Boolean).forEach(name=>permissions.push({id:`p${++seq}`,module,name,type:'permission'})));
Object.entries(screens).forEach(([screen,subs])=>{const parent=`p${++seq}`;permissions.push({id:parent,module:'PANTALLAS',name:screen,type:'global',screen});subs.split('|').filter(Boolean).forEach(name=>permissions.push({id:`p${++seq}`,module:'PANTALLAS',name,type:'sub',screen,parent}));});
const defaultsDeny=new Set(['Eliminar cita','Modificar coste de cancelación','Actualizar puntos de cliente','Cancel Membership','Eliminar cliente','Refund Membership','Resubscribe Membership','Suspend Membership','Waive Membership','Cambiar comisiones del empleado','Cambiar detalles de empleados','Eliminar habilidades','Añadir entrada del horario','Cambiar horas actuales','Cambiar horas programadas','Eliminar entrada del horario','Borrar una transacción','Reembolsar transacción','Activar o desactivar seguridad','Borrar el registro','Cambiar el PIN de otro empleado','Cambiar huella de otro empleado','Can Upgrade','Change own PIN','Conectar y desconectar otros empleados','Configurar la contraseña de inicio','Huella dactilar puede ser asignada','Cambiar detalles de bonos','Cambiar detalles de servicios','Cambiar precio servicio','Cambiar servicios de habilidades','Cambiar cantidad de stock','Cambiar código de barras del producto','Cambiar configuración de reorder','Cambiar coste medio','Cambiar detalles de stock','Cambiar el precio de venta de producto','Cambiar precio de compra del producto','Crear productos','Change Other Employee Visit Notes','Delete Other Employee Visit Notes']);
const stockReports=new Set(['Stock: Etiquetas de producto para estanterías','Stock: Formulario de artículos no listados','Stock: Historial de movimientos de stock','Stock: Listado de precios de productos','Stock: Pedidos pendientes','Stock: Stock recibido','Stock: Sumario de stock recibido']);
const STORAGE='matriz-seguridad-v1';let state;try{state=JSON.parse(localStorage.getItem(STORAGE))||{}}catch{state={}};
if(!state.values)state.values={};
permissions.forEach(p=>{const k=`Control de Stock|${p.id}`;if(state.values[k]===undefined){if(p.module==='ITEMS / REPORTES')state.values[k]=stockReports.has(p.name)?'allow':'deny';else if(p.module==='PANTALLAS')state.values[k]=p.type==='global'?(p.name==='Stock'?'allow':'deny'):null;else state.values[k]=defaultsDeny.has(p.name)?'deny':'allow';}});
let currentProfile=state.currentProfile||PROFILES[0],moduleFilter='all',statusFilter='all',search='';
const $=s=>document.querySelector(s),esc=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function value(p){return state.values[`${currentProfile}|${p.id}`]||null}function blocked(p){return p.type==='sub'&&state.values[`${currentProfile}|${p.parent}`]==='deny'}
function save(){state.currentProfile=currentProfile;localStorage.setItem(STORAGE,JSON.stringify(state));$('#saveStatus').textContent='Guardado ahora';setTimeout(()=>$('#saveStatus').textContent='Guardado en este dispositivo',1400)}
function countsAsRequired(p){return !blocked(p)}
function filtered(){return permissions.filter(p=>(moduleFilter==='all'||p.module===moduleFilter)&&(!search||`${p.name} ${p.module} ${p.screen||''}`.toLowerCase().includes(search))&&(statusFilter==='all'||(statusFilter==='pending'&&!value(p)&&countsAsRequired(p))||value(p)===statusFilter))}
function render(){const list=filtered();$('#resultCount').textContent=`${list.length} ${list.length===1?'permiso':'permisos'}`;$('#contextHint').textContent=moduleFilter==='all'?'Mostrando el catálogo completo':`Filtrado por ${moduleFilter}`;let html='',last='';list.forEach(p=>{if(p.module!==last){last=p.module;html+=`<h3 class="module-heading">${esc(last)} <span>${list.filter(x=>x.module===last).length}</span></h3>`}const v=value(p),isBlocked=blocked(p);html+=`<article class="card ${p.type==='global'?'global':''} ${p.type==='sub'?'child':''} ${isBlocked?'disabled':''}"><div><div class="permission-name">${p.type==='sub'?'↳ ':''}${esc(p.name)}</div><div class="permission-meta">${p.type==='global'?'<span class="global-tag">Acceso global a pantalla</span>':p.type==='sub'?`Subpermiso de ${esc(p.screen)}`:esc(p.module)}</div></div><div class="choices"><button class="choice allow ${v==='allow'?'selected':''}" data-id="${p.id}" data-v="allow" ${isBlocked?'disabled':''}>✓ Aplica</button><button class="choice deny ${v==='deny'?'selected':''}" data-id="${p.id}" data-v="deny" ${isBlocked?'disabled':''}>× Sin acceso</button></div></article>`});$('#permissionList').innerHTML=html;$('#emptyState').hidden=!!list.length;updateSummary()}
function updateSummary(){const required=permissions.filter(countsAsRequired),defined=required.filter(p=>value(p));const pct=required.length?Math.round(defined.length/required.length*100):100;$('#profileTitle').textContent=currentProfile;$('#progressText').textContent=`${defined.length} de ${required.length} permisos necesarios definidos`;$('#progressPct').textContent=`${pct}%`;$('#progressRing').style.setProperty('--p',pct)}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2200)}
PROFILES.forEach(p=>$('#profileSelect').add(new Option(p,p)));$('#profileSelect').value=currentProfile;[...new Set(permissions.map(p=>p.module))].forEach(m=>$('#moduleSelect').add(new Option(m,m)));
['Todos','Pendientes','PANTALLAS','AGENDA','CLIENTES','STOCK','ITEMS / REPORTES'].forEach((t,i)=>{const b=document.createElement('button');b.className='tab'+(i===0?' active':'');b.textContent=t;b.dataset.m=t==='Todos'||t==='Pendientes'?'all':t;b.dataset.pending=t==='Pendientes';$('#quickTabs').append(b)});
$('#permissionList').addEventListener('click',e=>{const b=e.target.closest('[data-id]');if(!b)return;state.values[`${currentProfile}|${b.dataset.id}`]=b.dataset.v;save();render()});
$('#profileSelect').onchange=e=>{currentProfile=e.target.value;save();render()};$('#moduleSelect').onchange=e=>{moduleFilter=e.target.value;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.m===moduleFilter&&!x.dataset.pending));render()};$('#statusSelect').onchange=e=>{statusFilter=e.target.value;render()};$('#searchInput').oninput=e=>{search=e.target.value.trim().toLowerCase();render()};
$('#quickTabs').onclick=e=>{const b=e.target.closest('.tab');if(!b)return;document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');moduleFilter=b.dataset.m;statusFilter=b.dataset.pending?'pending':'all';$('#moduleSelect').value=moduleFilter;$('#statusSelect').value=statusFilter;render()};
function bulk(v){const list=filtered().filter(p=>!blocked(p));if(!list.length)return;list.forEach(p=>state.values[`${currentProfile}|${p.id}`]=v);save();render();toast(`${list.length} permisos actualizados`)}$('#allAllow').onclick=()=>bulk('allow');$('#allDeny').onclick=()=>bulk('deny');
$('#exportBtn').onclick=()=>{const payload={app:'Matriz de Seguridad',version:1,exportedAt:new Date().toISOString(),profiles:PROFILES,permissions,state};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`matriz-seguridad-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);toast('Copia exportada')};
$('#saveBtn').onclick=()=>{save();toast('Cambios guardados en este dispositivo')};
$('#importBtn').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(!data.state?.values)throw 0;state=data.state;currentProfile=state.currentProfile||PROFILES[0];$('#profileSelect').value=currentProfile;save();render();toast('Avance importado correctamente')}catch{toast('El archivo no es una copia válida')}e.target.value=''};
render();
